require_relative 'code.rb'

class Game

  @code
  @score
  @guesses
  @GUESS_MAX

  attr_reader :code, :guesses, :GUESS_MAX
  attr_accessor :score


  def initialize
    @code = Code.new()
    @score = ['', '']
    @guesses = 0
    @GUESS_MAX = 2
    print_intro
  end
  
  
  def increment_guesses
    @guesses += 1
  end
  
  
  def win?
    @score[0] == 'XXXX' ? true : false
  end


  def display_score
    puts @score[0] == '' ? '-' : @score[0]
    puts @score[1] == '' ? '-' : @score[1]
    puts"\n"
  end
  
  
  private

  def print_intro
    puts "Play Mastermind
---------------
Guess the four digit code generated by the computer.\n
Digits can be from 1 to 6.
1   2   3   4   5   6\n
After your guess, feedback is given:
  X means you guessed the right digit in the right position.
  O means you guessed the right digit but in the wrong position.\n
You have #{@GUESS_MAX} guesses.\n
Enter a 4 digit number, with each digit between 1 and 6 eg. 2146."
  end

end